#FindZLIB.cmake:FIND_PACKAGE_HANDLE_STANDARD_ARGS(libpcre_static REQUIRED_VARS LIBPCRE_LIBRARY LIBPCRE_INCLUDE_DIR VERSION_VAR LIBPCRE_VERSION HANDLE_COMPONENTS) 
if(NOT TARGET libpcre)
  set(LIBNAME pcre-8.42)
  set(${LIBNAME}_DIR ${CMAKE_CURRENT_LIST_DIR}/../thirdparty/${LIBNAME})
  message("${LIBNAME}_DIR:${${LIBNAME}_DIR}")
  if(CMAKE_SYSTEM_NAME MATCHES "Linux")
    add_compile_definitions(DYZ)
  endif()
  set(PCRE_BUILD_TESTS OFF)
  add_subdirectory(${${LIBNAME}_DIR}/)
  if (NOT LIBPCRE_INCLUDE_DIR)
    set (LIBPCRE_INCLUDE_DIR ${${LIBNAME}_DIR}/include ${${LIBNAME}_DIR}/ ${CMAKE_BINARY_DIR}/thirdparty/${LIBNAME} )
  endif()
endif()

include_directories(${LIBPCRE_INCLUDE_DIR})

set(LIBPCRE_LIBRARY   $<TARGET_OBJECTS:pcre>  $<TARGET_OBJECTS:pcreposix> $<TARGET_OBJECTS:pcre16>  $<TARGET_OBJECTS:pcre32> $<TARGET_OBJECTS:pcrecpp> )
set(LIBPCRE_LIBRARIES $<TARGET_OBJECTS:pcre>  $<TARGET_OBJECTS:pcreposix> $<TARGET_OBJECTS:pcre16>  $<TARGET_OBJECTS:pcre32> $<TARGET_OBJECTS:pcrecpp> )
