if(NOT TARGET sqlite3)
  set(LIBNAME sqlite3)
endif()

if("$ENV{HomeDir}" STREQUAL "")
    if(CMAKE_HOST_SYSTEM_NAME MATCHES "Linux")
        set(ALL_LIB_HOME_DIR ${CMAKE_CURRENT_LIST_DIR}/../out/linux)
    elseif(CMAKE_HOST_SYSTEM_NAME MATCHES "Windows")
        set(ALL_LIB_HOME_DIR ${CMAKE_CURRENT_LIST_DIR}/../out/windows)
        string(REPLACE "/" "\\" ALL_LIB_HOME_DIR "${ALL_LIB_HOME_DIR}")
    else()
        message("current platform: unkonw ") 
    endif()
else()
    set(ALL_LIB_HOME_DIR "$ENV{HomeDir}")
endif()

set(SQLITE3_ROOT_DIR     ${ALL_LIB_HOME_DIR}/${LIBNAME})
set(SQLITE3_INCLUDE_DIRS ${SQLITE3_ROOT_DIR}/include)
set(SQLITE3_LIBRARY_DIRS ${SQLITE3_ROOT_DIR}/lib)
set(SQLITE3_LIBRARY      SQLITE3_static)
set(SQLITE3_LIBRARIES    SQLITE3_static)
