if(NOT TARGET boost)
    set(LIBNAME boost)
    if(CMAKE_HOST_SYSTEM_NAME MATCHES "Linux")
        set(ALL_LIB_HOME_DIR ${CMAKE_CURRENT_LIST_DIR}/../out/linux)
    elseif(CMAKE_HOST_SYSTEM_NAME MATCHES "Windows")
        set(ALL_LIB_HOME_DIR ${CMAKE_CURRENT_LIST_DIR}/../out/windows)
        string(REPLACE "/" "\\" ALL_LIB_HOME_DIR "${ALL_LIB_HOME_DIR}")
        message("[INFO] ${CMAKE_HOST_SYSTEM_NAME}  ALL_LIB_HOME_DIR: ${ALL_LIB_HOME_DIR}")
    else()
        message("[ERROR] current platform: unkonw ") 
    endif()
    
    if(NOT EXISTS "${ALL_LIB_HOME_DIR}/${LIBNAME}")
        set(DISK_NAME_LIST C D E F G)
        set(LIB_HOME_DIR_LIST   Programs Program)
        foreach(DISK_NAME ${DISK_NAME_LIST})
            foreach(LIB_HOME_DIR ${LIB_HOME_DIR_LIST})
                if(EXISTS "${DISK_NAME}:/${LIB_HOME_DIR}/${LIBNAME}")
                    set(ALL_LIB_HOME_DIR "${DISK_NAME}:/${LIB_HOME_DIR}")
                    message("[INFO] ALL_LIB_HOME_DIR: ${ALL_LIB_HOME_DIR}")
                else()
                    message("[INFO] Skip LIB_HOME_DIR:${DISK_NAME}:/${LIB_HOME_DIR}")
                endif()
            endforeach()
        endforeach()
    else()
        message("[INFO] ALL_LIB_HOME_DIR: ${ALL_LIB_HOME_DIR}")
    endif()
endif()

set(BOOST_ROOT_DIR     ${ALL_LIB_HOME_DIR}/${LIBNAME})

set(BOOST_INCLUDE_DIRS ${BOOST_ROOT_DIR}/include)
set(BOOST_LIBRARY_DIRS ${BOOST_ROOT_DIR}/lib)

set(BOOST_LIBRARY      BOOST_static)
set(BOOST_LIBRARIES    BOOST_static)

include_directories(${BOOST_INCLUDE_DIRS})
link_directories   (${BOOST_LIBRARY_DIRS})
