if(NOT TARGET crypto)
  set(LIBNAME crypto)
endif()

if("$ENV{HomeDir}" STREQUAL "")
    if(CMAKE_HOST_SYSTEM_NAME MATCHES "Linux")
        set(ALL_LIB_HOME_DIR ${CMAKE_CURRENT_LIST_DIR}/../out/linux)
    elseif(CMAKE_HOST_SYSTEM_NAME MATCHES "Windows")
        set(ALL_LIB_HOME_DIR ${CMAKE_CURRENT_LIST_DIR}/../out/windows)
        string(REPLACE "/" "\\" ALL_LIB_HOME_DIR "${ALL_LIB_HOME_DIR}")
    else()
        message("current platform: unkonw ") 
    endif()
else()
    set(ALL_LIB_HOME_DIR "$ENV{HomeDir}")
endif()

set(CRYPTO_ROOT_DIR     ${ALL_LIB_HOME_DIR}/${LIBNAME})
set(CRYPTO_INCLUDE_DIRS ${CRYPTO_ROOT_DIR}/include)
set(CRYPTO_LIBRARY_DIRS ${CRYPTO_ROOT_DIR}/lib)
set(CRYPTO_LIBRARY      CRYPTO_static)
set(CRYPTO_LIBRARIES    CRYPTO_static)
