if(NOT TARGET json)
  set(LIBNAME json)
endif()

if("$ENV{HomeDir}" STREQUAL "")
    if(CMAKE_HOST_SYSTEM_NAME MATCHES "Linux")
        set(ALL_LIB_HOME_DIR ${CMAKE_CURRENT_LIST_DIR}/../out/linux)
    elseif(CMAKE_HOST_SYSTEM_NAME MATCHES "Windows")
        set(ALL_LIB_HOME_DIR ${CMAKE_CURRENT_LIST_DIR}/../out/windows)
        string(REPLACE "/" "\\" ALL_LIB_HOME_DIR "${ALL_LIB_HOME_DIR}")
    else()
        message("current platform: unkonw ") 
    endif()
else()
    set(ALL_LIB_HOME_DIR "$ENV{HomeDir}")
endif()

set(JSON_ROOT_DIR     ${ALL_LIB_HOME_DIR}/${LIBNAME})
set(JSON_INCLUDE_DIRS ${JSON_ROOT_DIR}/include)
set(JSON_LIBRARY_DIRS ${JSON_ROOT_DIR}/lib)
set(JSON_LIBRARY      JSON_static)
set(JSON_LIBRARIES    JSON_static)
